import type { ReactNode } from 'react';
import { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { 
  signIn, 
  signUp, 
  signOut, 
  getCurrentUser,
  confirmSignUp,
  fetchUserAttributes
} from 'aws-amplify/auth';
import { generateClient } from 'aws-amplify/api';
import type { Couple, Expense, Settlement, User, Balance, HistoryConnection, HistoryQueryOptions } from '../types';
import { calculateBalance } from '../utils/helpers';

// GraphQL query for getCoupleHistory (will be generated by amplify codegen)
const getCoupleHistory = /* GraphQL */ `
  query GetCoupleHistory(
    $coupleId: ID!
    $limit: Int
    $nextToken: String
    $typeFilter: String
    $categoryFilter: String
    $paidByFilter: String
  ) {
    getCoupleHistory(
      coupleId: $coupleId
      limit: $limit
      nextToken: $nextToken
      typeFilter: $typeFilter
      categoryFilter: $categoryFilter
      paidByFilter: $paidByFilter
    ) {
      items {
        id
        type
        date
        createdAt
        amount
        paidBy
        description
        category
        splitType
        partner1Share
        partner2Share
        paidTo
        note
      }
      nextToken
      totalCount
    }
  }
`;

// Trusted mutations - these go through the Lambda write service
const createCoupleTrustedMutation = /* GraphQL */ `
  mutation CreateCoupleTrusted($input: CreateCoupleInput!) {
    createCoupleTrusted(input: $input) {
      success
      error
      clientMutationId
      couple {
        id
        owners
        name
        partner1Id
        partner1Name
        partner1Email
        partner2Id
        partner2Name
        partner2Email
        inviteCode
        defaultSplitPercent
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        createdAt
        updatedAt
      }
    }
  }
`;

const joinCoupleByInviteCodeMutation = /* GraphQL */ `
  mutation JoinCoupleByInviteCode($input: JoinCoupleInput!) {
    joinCoupleByInviteCode(input: $input) {
      success
      error
      clientMutationId
      couple {
        id
        owners
        name
        partner1Id
        partner1Name
        partner1Email
        partner2Id
        partner2Name
        partner2Email
        inviteCode
        defaultSplitPercent
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        createdAt
        updatedAt
      }
    }
  }
`;

const createExpenseTrustedMutation = /* GraphQL */ `
  mutation CreateExpenseTrusted($input: CreateExpenseInput!) {
    createExpenseTrusted(input: $input) {
      success
      error
      clientMutationId
      expense {
        id
        owners
        coupleId
        description
        amount
        paidBy
        splitType
        partner1Share
        partner2Share
        category
        date
        note
        createdAt
        updatedAt
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

const updateExpenseTrustedMutation = /* GraphQL */ `
  mutation UpdateExpenseTrusted($input: UpdateExpenseInput!) {
    updateExpenseTrusted(input: $input) {
      success
      error
      clientMutationId
      expense {
        id
        owners
        coupleId
        description
        amount
        paidBy
        splitType
        partner1Share
        partner2Share
        category
        date
        note
        createdAt
        updatedAt
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

const deleteExpenseTrustedMutation = /* GraphQL */ `
  mutation DeleteExpenseTrusted($input: DeleteExpenseInput!) {
    deleteExpenseTrusted(input: $input) {
      success
      error
      clientMutationId
      expense {
        id
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

const createSettlementTrustedMutation = /* GraphQL */ `
  mutation CreateSettlementTrusted($input: CreateSettlementInput!) {
    createSettlementTrusted(input: $input) {
      success
      error
      clientMutationId
      settlement {
        id
        owners
        coupleId
        amount
        paidBy
        paidTo
        date
        note
        createdAt
        updatedAt
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

const updateSettlementTrustedMutation = /* GraphQL */ `
  mutation UpdateSettlementTrusted($input: UpdateSettlementInput!) {
    updateSettlementTrusted(input: $input) {
      success
      error
      clientMutationId
      settlement {
        id
        owners
        coupleId
        amount
        paidBy
        paidTo
        date
        note
        createdAt
        updatedAt
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

const deleteSettlementTrustedMutation = /* GraphQL */ `
  mutation DeleteSettlementTrusted($input: DeleteSettlementInput!) {
    deleteSettlementTrusted(input: $input) {
      success
      error
      clientMutationId
      settlement {
        id
      }
      couple {
        id
        expenseCount
        settlementCount
        partner1TotalPaid
        partner2TotalPaid
        partner1TotalOwes
        partner2TotalOwes
        netBalance
        lastCalculatedAt
        updatedAt
      }
    }
  }
`;

import * as queries from '../graphql/queries';
import * as mutations from '../graphql/mutations';

// Lazy GraphQL client - only created after Amplify is configured
// Uses userPool auth for owner-based authorization
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _client: any = null;
const getClient = () => {
  if (!_client) {
    _client = generateClient({ authMode: 'userPool' });
  }
  return _client;
};

interface AppContextType {
  // Auth state
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  needsConfirmation: boolean;
  pendingEmail: string | null;
  login: (email: string, password: string) => Promise<{ success: boolean; error?: string }>;
  signup: (email: string, password: string, name: string) => Promise<{ success: boolean; needsConfirmation?: boolean; error?: string }>;
  confirmAccount: (code: string) => Promise<{ success: boolean; error?: string }>;
  logout: () => Promise<void>;

  // Couple state
  couple: Couple | null;
  createCouple: (name: string, partnerName: string) => Promise<{ success: boolean; error?: string }>;
  joinCouple: (inviteCode: string, partnerName: string) => Promise<{ success: boolean; error?: string }>;
  updateCouple: (updates: Partial<Couple>) => Promise<void>;

  // Expenses
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, 'id' | 'coupleId' | 'createdAt' | 'updatedAt'>) => Promise<void>;
  addExpenseBatch: (
    expenses: Array<Omit<Expense, 'id' | 'coupleId' | 'createdAt' | 'updatedAt'>>
  ) => Promise<{ created: number; failed: number }>;
  updateExpense: (id: string, updates: Partial<Expense>) => Promise<void>;
  deleteExpense: (id: string) => Promise<void>;

  // Settlements
  settlements: Settlement[];
  addSettlement: (settlement: Omit<Settlement, 'id' | 'coupleId' | 'createdAt'>) => Promise<void>;
  updateSettlement: (id: string, updates: Partial<Settlement>) => Promise<void>;
  deleteSettlement: (id: string) => Promise<void>;

  // Calculated values
  balance: Balance;
  
  // Paginated history query
  fetchHistory: (options: HistoryQueryOptions) => Promise<HistoryConnection>;
  
  // Refresh data
  refreshData: () => Promise<void>;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [couple, setCouple] = useState<Couple | null>(null);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [needsConfirmation, setNeedsConfirmation] = useState(false);
  const [pendingEmail, setPendingEmail] = useState<string | null>(null);

  // Helper to update couple with new aggregate values
  const updateCoupleAggregates = (updatedCoupleData: Partial<Couple>) => {
    setCouple(prev => prev ? { ...prev, ...updatedCoupleData } : null);
  };

  // Check for existing auth session on mount
  useEffect(() => {
    checkAuthState();
  }, []);

  const checkAuthState = async () => {
    try {
      const currentUser = await getCurrentUser();
      const attributes = await fetchUserAttributes();
      
      setUser({
        id: currentUser.userId,
        email: attributes.email || '',
        name: attributes.name || attributes.email?.split('@')[0] || 'User',
      });
      
      // Load user's couple data
      await loadUserData(currentUser.userId);
    } catch (error) {
      // Not signed in
      console.log('No authenticated user');
      setUser(null);
    } finally {
      setIsLoading(false);
    }
  };

  const loadUserData = async (userId: string) => {
    try {
      console.log('[loadUserData] Starting for userId:', userId);
      
      // Find couple where user is partner1 or partner2
      const coupleResult = await getClient().graphql({
        query: queries.listCouples,
        variables: {
          filter: {
            or: [
              { partner1Id: { eq: userId } },
              { partner2Id: { eq: userId } }
            ]
          }
        }
      });

      console.log('[loadUserData] Full query result:', JSON.stringify(coupleResult, null, 2));
      const couples = (coupleResult as any).data?.listCouples?.items || [];
      console.log('[loadUserData] Found couples:', couples.length, couples);
      
      if (couples.length > 0) {
        const userCouple = couples[0];
        console.log('[loadUserData] Setting couple:', userCouple.id, userCouple.name);
        setCouple(userCouple);
        
        // Load expenses and settlements for this couple
        await loadCoupleData(userCouple.id);
      } else {
        console.log('[loadUserData] No couples found for user');
      }
    } catch (error) {
      console.error('[loadUserData] Error loading user data:', error);
    }
  };

  const loadCoupleData = async (coupleId: string) => {
    try {
      console.log('Loading couple data for coupleId:', coupleId);
      
      // Load expenses (now with sort key on date)
      const expenseResult = await getClient().graphql({
        query: queries.expensesByCoupleIdAndDate,
        variables: { 
          coupleId,
          sortDirection: 'DESC'
        }
      });
      console.log('Expense query result:', expenseResult);
      const loadedExpenses = (expenseResult as any).data?.expensesByCoupleIdAndDate?.items || [];
      console.log('Loaded expenses:', loadedExpenses.length, loadedExpenses);
      setExpenses(loadedExpenses);

      // Load settlements (now with sort key on date)
      const settlementResult = await getClient().graphql({
        query: queries.settlementsByCoupleIdAndDate,
        variables: { 
          coupleId,
          sortDirection: 'DESC'
        }
      });
      console.log('Settlement query result:', settlementResult);
      const loadedSettlements = (settlementResult as any).data?.settlementsByCoupleIdAndDate?.items || [];
      console.log('Loaded settlements:', loadedSettlements.length);
      setSettlements(loadedSettlements);
    } catch (error) {
      console.error('Error loading couple data:', error);
    }
  };

  const refreshData = useCallback(async () => {
    if (user) {
      await loadUserData(user.id);
    }
  }, [user]);

  // Auth functions
  const login = async (email: string, password: string): Promise<{ success: boolean; error?: string }> => {
    setIsLoading(true);
    try {
      const result = await signIn({ username: email, password });
      
      if (result.isSignedIn) {
        await checkAuthState();
        return { success: true };
      } else if (result.nextStep?.signInStep === 'CONFIRM_SIGN_UP') {
        setPendingEmail(email);
        setNeedsConfirmation(true);
        setIsLoading(false);
        return { success: false, error: 'Please verify your email first' };
      }
      
      return { success: false, error: 'Login failed' };
    } catch (error: any) {
      console.error('Login error:', error);
      setIsLoading(false);
      
      if (error.name === 'UserNotConfirmedException') {
        setPendingEmail(email);
        setNeedsConfirmation(true);
        return { success: false, error: 'Please verify your email first' };
      }
      
      return { success: false, error: error.message || 'Login failed' };
    }
  };

  const signup = async (email: string, password: string, name: string): Promise<{ success: boolean; needsConfirmation?: boolean; error?: string }> => {
    setIsLoading(true);
    try {
      const result = await signUp({
        username: email,
        password,
        options: {
          userAttributes: {
            email,
            name,
          },
        },
      });

      setIsLoading(false);
      
      if (result.isSignUpComplete) {
        return { success: true };
      } else {
        setPendingEmail(email);
        setNeedsConfirmation(true);
        return { success: true, needsConfirmation: true };
      }
    } catch (error: any) {
      console.error('Signup error:', error);
      setIsLoading(false);
      return { success: false, error: error.message || 'Signup failed' };
    }
  };

  const confirmAccount = async (code: string): Promise<{ success: boolean; error?: string }> => {
    if (!pendingEmail) {
      return { success: false, error: 'No pending email to confirm' };
    }

    try {
      await confirmSignUp({ username: pendingEmail, confirmationCode: code });
      setNeedsConfirmation(false);
      return { success: true };
    } catch (error: any) {
      console.error('Confirmation error:', error);
      return { success: false, error: error.message || 'Confirmation failed' };
    }
  };

  const logout = async () => {
    try {
      await signOut();
    } catch (error) {
      console.error('Logout error:', error);
    }
    setUser(null);
    setCouple(null);
    setExpenses([]);
    setSettlements([]);
    setNeedsConfirmation(false);
    setPendingEmail(null);
  };

  // Couple functions - using trusted mutations
  const createCouple = async (name: string, partnerName: string): Promise<{ success: boolean; error?: string }> => {
    if (!user) return { success: false, error: 'Not logged in' };

    try {
      console.log('[createCouple] Creating couple via trusted mutation');
      const result = await getClient().graphql({
        query: createCoupleTrustedMutation,
        variables: {
          input: {
            name,
            partnerName,
            defaultSplitPercent: 50,
          }
        }
      });

      const response = (result as any).data?.createCoupleTrusted;
      console.log('[createCouple] Response:', response);
      
      if (response?.success && response.couple) {
        setCouple(response.couple);
        return { success: true };
      }
      
      return { success: false, error: response?.error || 'Failed to create couple' };
    } catch (error: any) {
      console.error('Create couple error:', error);
      return { success: false, error: error.message || 'Failed to create couple' };
    }
  };

  const joinCouple = async (inviteCode: string, partnerName: string): Promise<{ success: boolean; error?: string }> => {
    if (!user) return { success: false, error: 'Not logged in' };

    try {
      console.log('[joinCouple] Joining couple via trusted mutation');
      const result = await getClient().graphql({
        query: joinCoupleByInviteCodeMutation,
        variables: {
          input: {
            inviteCode,
            partnerName,
          }
        }
      });

      const response = (result as any).data?.joinCoupleByInviteCode;
      console.log('[joinCouple] Response:', response);
      
      if (response?.success && response.couple) {
        setCouple(response.couple);
        await loadCoupleData(response.couple.id);
        return { success: true };
      }

      return { success: false, error: response?.error || 'Failed to join couple' };
    } catch (error: any) {
      console.error('Join couple error:', error);
      return { success: false, error: error.message || 'Failed to join couple' };
    }
  };

  const updateCouple = async (updates: Partial<Couple>) => {
    if (!couple) return;

    try {
      // For non-aggregate updates, still use the generated mutation
      // (updateCouple is for things like name, defaultSplitPercent)
      const result = await getClient().graphql({
        query: mutations.updateCouple,
        variables: {
          input: {
            id: couple.id,
            ...updates,
          }
        }
      });

      const updatedCouple = (result as any).data?.updateCouple;
      if (updatedCouple) {
        setCouple(updatedCouple);
      }
    } catch (error) {
      console.error('Update couple error:', error);
    }
  };

  // Expense functions - using trusted mutations
  const addExpense = async (expense: Omit<Expense, 'id' | 'coupleId' | 'createdAt' | 'updatedAt'>) => {
    if (!couple) return;

    try {
      console.log('[addExpense] Creating expense via trusted mutation');
      const result = await getClient().graphql({
        query: createExpenseTrustedMutation,
        variables: {
          input: {
            coupleId: couple.id,
            description: expense.description,
            amount: expense.amount,
            paidBy: expense.paidBy,
            splitType: expense.splitType,
            partner1Share: expense.partner1Share,
            partner2Share: expense.partner2Share,
            category: expense.category,
            date: expense.date,
            note: expense.note,
          }
        }
      });

      const response = (result as any).data?.createExpenseTrusted;
      console.log('[addExpense] Response:', response);
      
      if (response?.success && response.expense) {
        setExpenses(prev => [response.expense, ...prev]);
        // Update couple with new aggregates
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[addExpense] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Add expense error:', error);
    }
  };

  const addExpenseBatch: AppContextType['addExpenseBatch'] = async (batch) => {
    if (!couple) return { created: 0, failed: batch.length };

    console.log('[csv-import] addExpenseBatch.start', { count: batch.length, coupleId: couple.id });

    const created: Expense[] = [];
    let failed = 0;
    let latestCoupleData: Partial<Couple> | null = null;

    for (let i = 0; i < batch.length; i += 1) {
      const expense = batch[i];
      try {
        const result = await getClient().graphql({
          query: createExpenseTrustedMutation,
          variables: {
            input: {
              coupleId: couple.id,
              description: expense.description,
              amount: expense.amount,
              paidBy: expense.paidBy,
              splitType: expense.splitType,
              partner1Share: expense.partner1Share,
              partner2Share: expense.partner2Share,
              category: expense.category,
              date: expense.date,
              note: expense.note,
            }
          }
        });

        const response = (result as any).data?.createExpenseTrusted;
        if (response?.success && response.expense) {
          created.push(response.expense);
          if (response.couple) {
            latestCoupleData = response.couple;
          }
        } else {
          failed += 1;
          console.warn('[csv-import] addExpenseBatch.failed', { index: i, error: response?.error });
        }
      } catch (error) {
        failed += 1;
        console.error('[csv-import] addExpenseBatch.itemError', { index: i, error });
      }

      if ((i + 1) % 25 === 0) {
        console.log('[csv-import] addExpenseBatch.progress', { done: i + 1, total: batch.length, created: created.length, failed });
      }
    }

    if (created.length > 0) {
      setExpenses((prev) => {
        const next = [...created, ...prev];
        next.sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime());
        return next;
      });
    }

    // Update couple with final aggregates
    if (latestCoupleData) {
      updateCoupleAggregates(latestCoupleData);
    }

    console.log('[csv-import] addExpenseBatch.done', { created: created.length, failed });
    return { created: created.length, failed };
  };

  const updateExpense = async (id: string, updates: Partial<Expense>) => {
    try {
      console.log('[updateExpense] Updating expense via trusted mutation');
      const result = await getClient().graphql({
        query: updateExpenseTrustedMutation,
        variables: {
          input: {
            id,
            description: updates.description,
            amount: updates.amount,
            paidBy: updates.paidBy,
            splitType: updates.splitType,
            partner1Share: updates.partner1Share,
            partner2Share: updates.partner2Share,
            category: updates.category,
            date: updates.date,
            note: updates.note,
          }
        }
      });

      const response = (result as any).data?.updateExpenseTrusted;
      console.log('[updateExpense] Response:', response);
      
      if (response?.success && response.expense) {
        setExpenses(prev =>
          prev.map(exp => (exp.id === id ? response.expense : exp))
        );
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[updateExpense] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Update expense error:', error);
    }
  };

  const deleteExpense = async (id: string) => {
    try {
      console.log('[deleteExpense] Deleting expense via trusted mutation');
      const result = await getClient().graphql({
        query: deleteExpenseTrustedMutation,
        variables: {
          input: { id }
        }
      });

      const response = (result as any).data?.deleteExpenseTrusted;
      console.log('[deleteExpense] Response:', response);
      
      if (response?.success) {
        setExpenses(prev => prev.filter(exp => exp.id !== id));
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[deleteExpense] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Delete expense error:', error);
    }
  };

  // Settlement functions - using trusted mutations
  const addSettlement = async (settlement: Omit<Settlement, 'id' | 'coupleId' | 'createdAt'>) => {
    if (!couple) return;

    try {
      console.log('[addSettlement] Creating settlement via trusted mutation');
      const result = await getClient().graphql({
        query: createSettlementTrustedMutation,
        variables: {
          input: {
            coupleId: couple.id,
            amount: settlement.amount,
            paidBy: settlement.paidBy,
            paidTo: settlement.paidTo,
            date: settlement.date,
            note: settlement.note,
          }
        }
      });

      const response = (result as any).data?.createSettlementTrusted;
      console.log('[addSettlement] Response:', response);
      
      if (response?.success && response.settlement) {
        setSettlements(prev => [response.settlement, ...prev]);
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[addSettlement] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Add settlement error:', error);
    }
  };

  const updateSettlement = async (id: string, updates: Partial<Settlement>) => {
    try {
      console.log('[updateSettlement] Updating settlement via trusted mutation');
      const result = await getClient().graphql({
        query: updateSettlementTrustedMutation,
        variables: {
          input: {
            id,
            amount: updates.amount,
            paidBy: updates.paidBy,
            paidTo: updates.paidTo,
            date: updates.date,
            note: updates.note,
          }
        }
      });

      const response = (result as any).data?.updateSettlementTrusted;
      console.log('[updateSettlement] Response:', response);
      
      if (response?.success && response.settlement) {
        setSettlements(prev =>
          prev.map(s => (s.id === id ? response.settlement : s))
        );
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[updateSettlement] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Update settlement error:', error);
    }
  };

  const deleteSettlement = async (id: string) => {
    try {
      console.log('[deleteSettlement] Deleting settlement via trusted mutation');
      const result = await getClient().graphql({
        query: deleteSettlementTrustedMutation,
        variables: {
          input: { id }
        }
      });

      const response = (result as any).data?.deleteSettlementTrusted;
      console.log('[deleteSettlement] Response:', response);
      
      if (response?.success) {
        setSettlements(prev => prev.filter(s => s.id !== id));
        if (response.couple) {
          updateCoupleAggregates(response.couple);
        }
      } else {
        console.error('[deleteSettlement] Failed:', response?.error);
      }
    } catch (error) {
      console.error('Delete settlement error:', error);
    }
  };

  // Paginated history query
  const fetchHistory = async (options: HistoryQueryOptions): Promise<HistoryConnection> => {
    try {
      console.log('[fetchHistory] Querying with options:', options);
      const result = await getClient().graphql({
        query: getCoupleHistory,
        variables: {
          coupleId: options.coupleId,
          limit: options.limit || 20,
          nextToken: options.nextToken || null,
          typeFilter: options.typeFilter || null,
          categoryFilter: options.categoryFilter || null,
          paidByFilter: options.paidByFilter || null,
        }
      });

      const data = (result as any).data?.getCoupleHistory;
      console.log('[fetchHistory] Result:', data);
      
      return {
        items: data?.items || [],
        nextToken: data?.nextToken || null,
        totalCount: data?.totalCount || 0,
      };
    } catch (error) {
      console.error('[fetchHistory] Error:', error);
      return {
        items: [],
        nextToken: null,
        totalCount: 0,
      };
    }
  };

  // Calculate balance - prefer pre-computed aggregates from couple, fallback to client-side
  const balance: Balance = (() => {
    // If couple has pre-computed aggregates, use them
    if (couple && typeof couple.netBalance === 'number') {
      return {
        amount: couple.netBalance,
        partner1Total: couple.partner1TotalPaid || 0,
        partner2Total: couple.partner2TotalPaid || 0,
      };
    }
    // Fallback to client-side calculation (for backwards compatibility)
    return calculateBalance(expenses, settlements);
  })();

  const value: AppContextType = {
    user,
    isAuthenticated: !!user,
    isLoading,
    needsConfirmation,
    pendingEmail,
    login,
    signup,
    confirmAccount,
    logout,
    couple,
    createCouple,
    joinCouple,
    updateCouple,
    expenses,
    addExpense,
    addExpenseBatch,
    updateExpense,
    deleteExpense,
    settlements,
    addSettlement,
    updateSettlement,
    deleteSettlement,
    balance,
    fetchHistory,
    refreshData,
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
